### ISSUE TITLE
[Question] Difference Sempy

### ISSUE THREAD

**Issue by Daandamhuis** [m-kovalsky/fabric_cat_tools#11]
Hi,

Quick question, what is the difference between the Sempy package and this package? Will these be merged or will they co-exist?

Thanks for your efforts, it will help us when migrating certain models in our landscape.

Thanks!

**Comment by m-kovalsky** [comment]
That's a great question. This library servers as a quasi extension of semantic-link (sempy). We will have to see regarding the future. The more people who find value in this library, the more likely it is to merge into semantic-link at some point in the future.
