### ISSUE TITLE
Can we extract show_unsupported_direct_lake_objects() output!?

### ISSUE THREAD

**Issue by cvlmonica** [m-kovalsky/fabric_cat_tools#14]
For a given import/directquery semantic model I am trying to capture the unsupported objects in direct lake mode using  the function show_unsupported_direct_lake_objects().

I get to see the output but is there any way to convert it into dataframe or load into a table?
is there anyway to capture the output!?

**Comment by m-kovalsky** [comment]
I will update the function so that it outputs 3 dataframes instead of displaying them. Then, users can opt to display them or store them if so desired.

The new syntax will be like this.

```python
dfT, dfC, dfR = fct.show_unsupported_direct_lake_objects(dataset = dataset_name, workspace = workspace_name)

# Optional to display each dataframe
display(dfT)
display(dfC)
display(dfR)
```

**Comment by cvlmonica** [comment]
Thank you so much that will be really helpful. Please do let me know once the function is updated.

**Comment by m-kovalsky** [comment]
It will be available in the next release, stay tuned.

**Comment by cvlmonica** [comment]
Thank you so much for the information and quick response!
