### ISSUE TITLE
Enhancement : Direct Lake Migration

### ISSUE THREAD

**Issue by cvlmonica** [m-kovalsky/fabric_cat_tools#15]
While doing the import/Direct query migration we have this function migrate_model_objects_to_semantic_model() , in this function what if we have an additional parameter where  we try to migrate only relationships/measures etc!?  Basically parameter based! 

Because while I was trying to run for a report since it has few relationships which are not supported it is throwing an error and stopping other things to run and migrate! rather than stopping everything! migrating 60% is good enough rather than getting an error and stopping the whole migration.

**Comment by m-kovalsky** [comment]
Thanks for raising this. The next version will not fail if it cannot create an object. It will not be necessary to add any additional parameters to solve this.

**Comment by cvlmonica** [comment]
Thank you!
