### ISSUE TITLE
Feature Suggestion : Validation Upon Migration to Direct Lake

### ISSUE THREAD

**Issue by cvlmonica** [m-kovalsky/fabric_cat_tools#16]
May be a function to check what is present in old report and what is there in new report a basic validation check!? would be known to the user that this is percent that has been migrated as such!?

for example:

s.no old-report    new-report    isMigrated      reason
1.    relationship   relationship        no             datetime/relationships are not supported 
      from  A to B    from  A to B

This is just my point of view but can be enhanced further as well.

**Comment by m-kovalsky** [comment]
This is a good idea. The next version will have a function which shows a list of all model objects and a True/False column indicating if it was migrated to the Direct Lake semantic model, and give a % migrated.

**Comment by cvlmonica** [comment]
Yeah if that can be stored in a dataframe along with the reason why it is not migrated as well for logging purposes would be really helpful!

**Comment by m-kovalsky** [comment]
Yes, the output will be a dataframe

**Comment by cvlmonica** [comment]
thank you!
