### ISSUE TITLE
[Question]  What are LocalDateTable_89898989 tables !??  

### ISSUE THREAD

**Issue by cvlmonica** [m-kovalsky/fabric_cat_tools#17]
When I am trying to run migrate_calc_tables_to_lakehouse() I am getting the below output though it ran successfully.
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/81950014/0abf584c-0b13-4d97-9e89-02ff7b90fe8c)

But for the next step that is to migrate all the objects it is throwing following error:
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/81950014/6260de3a-61d1-4035-a859-7db3efc83dc8)

What is the solution for this!?

**Comment by m-kovalsky** [comment]
Those are auto/date tables. It is a best practice to turn this feature off in Power BI Desktop. Migration of these tables is not supported.
https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-auto-date-time
