### ISSUE TITLE
list_shortcuts returns bad request, says unsupported

### ISSUE THREAD

**Issue by jamescl604** [m-kovalsky/fabric_cat_tools#18]
**Describe the bug**
When calling the list_shortcuts function it will return with "BadRequest","message":"The operation is not currently supported."

**To Reproduce**
1.  Call the function with a valid workspace id and lakehouse id, error is returned

**Expected behavior**
A list of shortcut information is returned

**Additional context**
The [rest api documentation](https://learn.microsoft.com/en-us/rest/api/fabric/core/onelake-shortcuts) doesn't show support for listing shortcuts, perhaps it's in private preview?  I sure hope a list method is supported as it will make life much easier.

https://learn.microsoft.com/en-us/rest/api/fabric/core/onelake-shortcuts

**Comment by m-kovalsky** [comment]
This API isn't official yet. It was working nonetheless for some time which is why I released this but now it seems it's not working. Once the API is made official this function will work as expected.

**Comment by jamescl604** [comment]
Thanks for confirming!
