### ISSUE TITLE
BPA Rule output Values

### ISSUE THREAD

**Issue by GilbertQue** [m-kovalsky/fabric_cat_tools#20]
Hi Michael, do you think it would be possible to have an output for the BPA Rules into a value/number.

The reason for this is so that I could run the BAP rules over a semantic model, then get a score. And from that score we could then determine if the semantic model passes or fails?

Thanks for all your amazing work!
Gilbert

**Comment by m-kovalsky** [comment]
How exactly do you envision this? What number would it give? Also maybe take the severity into context?

Also FYI, there is a parameter for this to return a dataframe (which you can transform) instead of the visualization.

**Comment by GilbertQue** [comment]
Hi Michael, I tried to but could not find the parameter?

If I can confirm the parameter then I am happy with that result?

**Comment by m-kovalsky** [comment]
See the documentation here: https://github.com/m-kovalsky/fabric_cat_tools?tab=readme-ov-file#run_model_bpa

The parameter is 'return_dataframe'

**Comment by GilbertQue** [comment]
Thanks Michael, let me give it a go tomorrow!

**Comment by GilbertQue** [comment]
I can see the output in the Pandas data frame. What I meant to say is instead of the visual icons could I get the severity number? 

Or alternatively what the visual icon relates to which severity (I can then create a number value from the icon)

Here is the example below.
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/72849240/062f7d03-81d7-4e84-88bc-0c1bc51d5e25)

**Comment by m-kovalsky** [comment]
I put a legend for the severity in the 'Returns' section of the documentation of this function.

https://github.com/m-kovalsky/fabric_cat_tools#run_model_bpa

**Comment by GilbertQue** [comment]
Awesome thanks for your answers!
