### ISSUE TITLE
[Question] can translate_semantic_model translate dim and fact table names?

### ISSUE THREAD

**Issue by BDOlode** [m-kovalsky/fabric_cat_tools#23]
Hi Kowalksy, thank you so much for extending the translate_semantic_model function in this new version. 

However, I am still not getting great results from this function, can it handle multiple words in a column name?
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/150895157/fc156ac6-6253-47d3-a05f-26d6095b2cd5)

**Comment by m-kovalsky** [comment]
What language(s) do you want to translate to?

**Comment by BDOlode** [comment]
In the previous message I attempted to translate to norwegian bokmal (nb). Running an expirement with the languague codes from the documentation gives similar results:
![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/150895157/44825c69-95e5-40c2-bf93-0ce27af7a961)

**Comment by m-kovalsky** [comment]
The language code you entered is not valid. You need to use:

languages = 'nb-NO'

**Comment by m-kovalsky** [comment]
It appears there is an issue with the ML library used by this function. I'm communicating with the team behind that library to rectify the issue.

**Comment by BDOlode** [comment]
Thank you! 🥇

**Comment by m-kovalsky** [comment]
Would you try this again. I tested it and it appears to be working fine. Just make sure to use the full 4 character language code i.e. 'nb-NO'
