### ISSUE TITLE
[Question] Can we get the information such as this semantic model is on top of this lakehouse? or so?

### ISSUE THREAD

**Issue by cvlmonica** [m-kovalsky/fabric_cat_tools#24]
Is there any way, to capture the semantic model is built on top of which lakehouse or warehouse?

**Comment by m-kovalsky** [comment]
This is for if the semantic model is built on a lakehouse (within the same workspace as the semantic model). 

https://github.com/m-kovalsky/fabric_cat_tools?tab=readme-ov-file#get_direct_lake_lakehouse

**Comment by cvlmonica** [comment]
Thank you got it!
