### ISSUE TITLE
0.3.3 version is not available

### ISSUE THREAD

**Issue by R1k91** [m-kovalsky/fabric_cat_tools#9]
https://raw.githubusercontent.com/m-kovalsky/fabric_cat_tools/main/fabric_cat_tools-0.3.3-py3-none-any.whl is giving back 404 error

you can reproduce the issue simply pasting the path in the browser address bar.

![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/57228476/fb751807-6c54-49ff-8515-617870e9746c)

![image](https://github.com/m-kovalsky/fabric_cat_tools/assets/57228476/bf407892-81b8-4df2-a6f0-47c116281b30)

**Comment by m-kovalsky** [comment]
Thanks. It's there now. I had posted in the release but not on the main page.

**Comment by R1k91** [comment]
it's working thank you!
